# Generated by Django 2.2.8 on 2019-12-02 11:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=19)),
                ('budgets', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
            options={
                'verbose_name': 'Expense Tracker',
                'verbose_name_plural': 'Expense Trackers',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TypeOfExpenses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Type of Expense',
                'verbose_name_plural': 'Type of Expenses',
                'ordering': ['-name'],
            },
        ),
    ]
